ITNFA-19: Added EnrollmentResult and moved findByPatientIdentifier to RegistrationCore
IsantePlus/openmrs-module-m2sys-biometrics pull request #11
Opened 2018-03-13 16:39 UTC by dserkowski

2018-03-13 16:50 UTC, dserkowski commented
Before this, [the PR in RegistrationCore](https://github.com/IsantePlus/openmrs-module-registrationcore/pull/11) should be merged

2018-03-13 17:00 UTC, pgesek approved these changes

2018-03-13 17:21 UTC, areklalo approved these changes

2018-03-16 13:17 UTC, pgesek requested changes

2018-03-16 13:17 UTC, pgesek commented on api/src/main/java/org/openmrs/module/m2sysbiometrics/util/impl/PatientHelperImpl.java
> +    private boolean isPatientIdentifierTypeExists(String patientIdentifierTypeUuid) {
drop the is part, you don't generally need it when using 'exists' in the name

2018-03-20 14:35 UTC, pawelcieszko approved these changes

2018-03-20 22:36 UTC, pawelcieszko approved these changes

2018-03-20 22:36 UTC, merged