ITOS-9: added ccd import during patient importing
IsantePlus/openmrs-module-m2sys-biometrics pull request #28
Opened 2018-04-12 12:45 UTC by pawelcieszko

2018-04-12 12:57 UTC, pawelcieszko commented
Due to sedish and haiti server malfunctions I wasn't able to test it properly so I suggest merging it after some testing.

2018-05-10 15:13 UTC, pgesek approved these changes

2018-05-17 10:36 UTC, oskarhinc requested changes
Why is there a jar file attached?

2018-05-17 10:37 UTC, oskarhinc approved these changes

2018-05-22 16:25 UTC, pgesek commented on api/src/main/java/org/openmrs/module/m2sysbiometrics/client/M2SysV105Client.java
> +                registrationService.importCcd(fingerScanStatus.getNationalBiometricSubject());
Can you catch all exceptions here, log and proceed on the failure

2018-05-22 17:08 UTC, pgesek approved these changes

2018-05-22 17:08 UTC, merged